/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface Users {
  bio: string;
  id?: number;
  is_sopt_member?: boolean | null;
  name: string;
}
export interface UsersFacebookAuth {
  facebook_access_token?: string | null;
  facebook_auth_id?: string | null;
  id?: number;
  user_id?: number | null;
}
