/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface AuthIdpFacebook {
  facebook_auth_id: string;
  id?: number;
  user_id: number;
}
export interface AuthServerConfig {
  id?: number;
  key: string;
  value: string;
}
export interface AuthSoptMember {
  email: string;
  generation: number;
  id?: number;
  joined?: boolean;
  name?: string | null;
}
export interface AuthUser {
  email?: string | null;
  generation: number;
  id?: number;
  name: string;
}
